---
- name: Manage MySQL Servers
  hosts: service_mysql       # היה: tag_Service_mysql
  become: yes
  remote_user: ec2-user
  roles:
    - mysql

- name: Manage Nginx Servers
  hosts: service_nginx       # היה: tag_Service_nginx
  become: yes
  remote_user: ec2-user
  roles:
    - nginx
