---
- name: Manage MySQL Servers
  hosts: service_mysql       
  become: yes
  remote_user: ec2-user
  roles:
    - mysql

- name: Manage Nginx Servers
  hosts: service_nginx      
  become: yes
  remote_user: ec2-user
  roles:
    - nginx
